#!/usr/bin/env python3
"""tools/validate_language_consistency.py — authorship-language gate.

Enforces the truth-aligned authorship vocabulary the site has settled on:

    "All content and code are reviewed manually before publication.
     Selective language model assistance may be used for drafting or
     structuring, but no automated publishing occurs."

The gate fails the build if any of a small set of inaccurate
"hand-written" / "fully manual" / "100% manual" phrases reappear in
public output. It is deliberately small: the brief calls for
truth-alignment, not anti-AI policing.

Allowlist:
  • Inline engineer-facing comments warning "do not edit by hand"
    (those are factually correct and address the maintainer, not
    the public).
  • Frozen archive files under public/integrity/releases/<YYYY-MM>/
    (sealed historical bytes; not rewritable).

Exit 0 = green; exit 1 = block.

Registered in tools/lib/checks.py (advisory tier).

Shape (deep module, small interface). The filesystem is the one injected seam —
`Repo(root)` — so the scan runs over a fixture repo with no monkeypatching.
`evaluate(repo)` is the pure compute path returning a Result; `main()` is the
only adapter that prints/exits. Byte-identical to the former
module-global PUBLIC_DIR walk.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(
    0,
    str(
        next(
            _a
            for _a in __import__("pathlib").Path(__file__).resolve().parents
            if _a.name == "tools"
        )
        / "lib"
    ),
)
from paths import REPO_ROOT  # noqa: E402
from repo import Repo  # noqa: E402  (shared filesystem evidence seam)

# banned phrases — case-insensitive, word-boundary regexes.
# `(?i)` not used so each pattern stays explicit.
BANNED_PATTERNS = [
    re.compile(r"\bhand[- ]written\b", re.IGNORECASE),
    re.compile(r"\bhandwritten\b", re.IGNORECASE),
    re.compile(r"\bwritten by hand\b", re.IGNORECASE),
    re.compile(r"\bhand[- ]crafted\b", re.IGNORECASE),
    re.compile(r"\bhand[- ]authored\b", re.IGNORECASE),
    re.compile(r"\bcrafted by hand\b", re.IGNORECASE),
    re.compile(r"\bentirely manual\b", re.IGNORECASE),
    re.compile(r"\bfully manual\b", re.IGNORECASE),
    re.compile(r"\b100% manual\b", re.IGNORECASE),
    re.compile(r"\bmanually authored\b", re.IGNORECASE),
    re.compile(r"\ball code written manually\b", re.IGNORECASE),
    re.compile(r"\ball content written manually\b", re.IGNORECASE),
]

# Engineer-facing safety warnings that talk about not editing
# generated files by hand. these are factually correct and address
# the maintainer; they are not public-facing authorship claims.
# we allowlist them by full-line match to keep the gate strict on
# everything else.
ALLOWLIST_LINES = {
    "  do not edit by hand.",  # sw.js / app.js header
    "// ⚠  This file is generated by generate_sw.py — do not edit by hand.",  # docs/sw-backup.js
    "fastest path is to drop the local service worker + its caches by hand.",  # docs/OPERATIONS.md
}

# file classes scanned. keep the brief's full list: html, css, js,
# json, txt, markdown, svg metadata are all in scope.
SCAN_GLOBS = ["*.html", "*.css", "*.js", "*.json", "*.txt", "*.md", "*.svg", "*.xml"]

# frozen archives + integrity manifests/sigs are excluded — sealed bytes.
EXCLUDE_DIR_PREFIXES = (
    "integrity/releases/2026-02",
    "integrity/releases/2026-04",
    "integrity/releases/2026-05",
)
EXCLUDE_FILE_EQUALS = {
    "integrity.json",
    "integrity.json.sig",
}


def _is_excluded(rel: str) -> bool:
    if rel in EXCLUDE_FILE_EQUALS:
        return True
    return any(rel.startswith(p) for p in EXCLUDE_DIR_PREFIXES)


@dataclass
class Result:
    fails: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.fails


# recursive public-tree walk — returns public-relative posix paths. the
# "public/" prefix and recursive walk live here in the validator, not on Repo.
def _public_glob(repo: Repo, pattern: str) -> list[str]:
    prefix = "public/"
    return [rel[len(prefix) :] for rel in repo.glob(f"{prefix}**/{pattern}")]


def evaluate(repo: Repo) -> Result:
    r = Result()

    for glob in SCAN_GLOBS:
        for rel in _public_glob(repo, glob):
            if _is_excluded(rel):
                continue
            try:
                text = repo.read(f"public/{rel}")
            except UnicodeDecodeError:
                continue
            for line_num, line in enumerate(text.splitlines(), 1):
                stripped = line.strip()
                # cheap allowlist short-circuit before regex work.
                if any(allow in line for allow in ALLOWLIST_LINES):
                    continue
                for pat in BANNED_PATTERNS:
                    if pat.search(line):
                        r.fails.append(
                            f"{rel}:{line_num} matches /{pat.pattern}/ — {stripped[:100]}"
                        )

    return r


def main(repo_root: Path = REPO_ROOT) -> int:
    repo = Repo(repo_root)
    r = evaluate(repo)

    if r.fails:
        print(f"FAIL: {len(r.fails)} authorship-language issue(s)", file=sys.stderr)
        for f in r.fails[:30]:
            print(f"  ✗ {f}", file=sys.stderr)
        if len(r.fails) > 30:
            print(f"  … and {len(r.fails) - 30} more", file=sys.stderr)
        print(file=sys.stderr)
        print("Reference wording:", file=sys.stderr)
        print('  "All content and code are reviewed manually before publication.', file=sys.stderr)
        print("   Selective language model assistance may be used for drafting or", file=sys.stderr)
        print('   structuring, but no automated publishing occurs."', file=sys.stderr)
        return 1

    print("OK: authorship language consistent")
    return 0


if __name__ == "__main__":
    sys.exit(main())
